language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"
        
env:
    - PLATFORMIO_CI_SRC=examples/SW10_North

install:
    - pip install -U platformio
    - platformio update

    - wget https://github.com/xinabox/arduino-CORE/archive/master.zip -O /tmp/arduino-CORE.zip
    - unzip /tmp/arduino-CORE.zip -d /tmp/
    
    - wget https://github.com/xinabox/arduino-SW10/archive/master.zip -O /tmp/arduino-SW10.zip
    - unzip /tmp/arduino-SW10.zip -d /tmp/

script:
    - platformio ci --lib="." --lib="/tmp/arduino-CORE-master" --lib="/tmp/arduino-SW10-master" --board=uno --board=zero --board=xinabox_cw01 --board=xinabox_cw02
